from __future__ import annotations

from pathlib import Path
from typing import Protocol

from winter_cli.modules.workspace.models import (
    DiffMode,
    FeatureWorktree,
    ProjectRepository,
    RepoDiffResult,
    RepoStatus,
    RepoSyncOutcome,
    StandaloneRepoStatus,
    StandaloneRepository,
    Workspace,
)


class ReadRepoRepository(Protocol):
    def get_workspace(self, root_path: Path, session_prefix: str) -> Workspace: ...
    def get_worktree_status(self, worktree: FeatureWorktree) -> RepoStatus: ...
    def get_standalone_status(self, repo: StandaloneRepository) -> StandaloneRepoStatus: ...
    def get_project_status(self, repo: ProjectRepository) -> RepoStatus: ...
    def get_diff(self, worktree: FeatureWorktree, mode: DiffMode) -> RepoDiffResult: ...


class WriteRepoRepository(ReadRepoRepository, Protocol):
    def fetch(self, worktree: FeatureWorktree) -> None: ...
    def sync_ff_or_merge(self, worktree: FeatureWorktree) -> RepoSyncOutcome: ...
    def sync_ff_only(self, repo: ProjectRepository) -> None: ...
    def set_upstream(self, worktree: FeatureWorktree, remote_branch: str) -> None: ...
    def unset_upstream(self, worktree: FeatureWorktree) -> None: ...
    def set_push_default(self, worktree: FeatureWorktree) -> None: ...
    def push(self, worktree: FeatureWorktree, feature_branch: str | None = None) -> int: ...
